POST http://localhost:4000/signup/null HTTP/1.1
content-type: application/json

{
    "username": "testuser1",
    "email": "saif501721@gmail.com",
    "password": "pass123",
    "phoneno": "1234567890"
}

###

POST http://172.23.179.217:4000/add/business HTTP/1.1
content-type: application/json

{
    "email": "test2@gmail.com",
    "businessname": "avocado",
    "tagline": "we suffer so you don't",
    "whatsappno": "138927348923742",
    "address": "jharkhand",
    "websiteurl": "http://website.com"
    
}

###

POST http://172.23.179.217:4000/add/political HTTP/1.1
content-type: application/json

{
    "email": "test2@gmail.com",
    "profilelogo": "asdasda.jpg",
    "partylogo": "dafwersfdfassdfsdf.jpg",
    "facebook": "facebook",
    "twitter": "facebook",
    "instagram": "twitter",
    "designation1": "designation1",
    "designation2": "designation2"
}


###

POST http://172.22.247.184:4000/signin HTTP/1.1
content-type: application/json

{
    "email": "saifkhan501721@gmail.com",
    "password": "pass12345"
}

###

POST http://172.22.247.184:4000/protected
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOiJiMTk5OTE4Yi1kZTlhLTRlYzgtYTBmMy00ZGUwZGEyMDIzN2UiLCJpYXQiOjE2NjM1MzE2NTQsImV4cCI6MTY2MzU0OTY1NH0.vTD7y_ffXlJIXS-qv2e9O3KjXY8fU7ZyIfujluZuXb0"
}

###
POST http://172.22.251.9:4000/userinfo
Content-Type: application/json

{
    "id": "b199918b-de9a-4ec8-a0f3-4de0da20237e"
}

###

POST http://localhost:4000/randomno HTTP/1.1
content-type: application/json

{
    "email": "saifkhan501721@gmail.com"
}

###

POST http://localhost:4000/verifyemail HTTP/1.1
content-type: application/json

{
    "email": "test2@gmail.com",
    "randomno" : 168886
}

###
GET http://localhost:4000/images


###

GET http://172.30.1.75:4000/delete

###

GET http://172.30.1.75:4000/image

###
POST http://172.30.1.163:4000/razorpay

###
POST http://172.22.246.21:4000/upload-image
Content-Type: application/json

{
    "email": "saifkhan501721@gmail.com",
    "image": "https://hindavidatabucket.s3.ap-south-1.amazonaws.com/next-s3-uploads/2010ab96-eb96-4d51-8b38-6b886213bf5d/first%2520ace.png"
}

###
GET http://172.22.251.148:4000/images