POST http://localhost:4000/signup/null HTTP/1.1
content-type: application/json

{
    "username": "testuser1",
    "email": "saif501721@gmail.com",
    "password": "pass123",
    "phoneno": "1234567890"
}

###

POST http://localhost:4000/add/business HTTP/1.1
content-type: application/json

{
    "email": "test2@gmail.com",
    "businessname": "avocado",
    "tagline": "we suffer so you don't",
    "whatsappno": "138927348923742",
    "address": "jharkhand",
    "websiteurl": "http://website.com"
    
}

###

POST http://localhost:4000/add/political HTTP/1.1
content-type: application/json

{
    "email": "test2@gmail.com",
    "partylogo": "dafwersfdfassdfsdf.jpg",
    "facebook": "facebook",
    "twitter": "facebook",
    "instagram": "twitter",
    "designation1": "designation1",
    "designation2": "designation2"
}


###

POST http://127.0.0.1:4000/signin HTTP/1.1
content-type: application/json

{
    "email": "saif501721@gmail.com",
    "password": "pass123"
}

###

POST http://localhost:4000/protected
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhaWY1MDE3MjFAZ21haWwuY29tIiwiaWF0IjoxNjU5NzYzMzYzLCJleHAiOjE2NTk3NjMzNzh9.6RBVdCcx1uDnJf1V_6bvO_7AbpqdFWM7MM8n7PXWilg"
}


###

POST http://localhost:4000/randomno HTTP/1.1
content-type: application/json

{
    "email": "saifkhan501721@gmail.com"
}

###

POST http://localhost:4000/verifyemail HTTP/1.1
content-type: application/json

{
    "email": "test2@gmail.com",
    "randomno" : 168886
}