POST http://localhost:4000/signup/de64e834-bf9a-43f1-b8ff-a8c4a028ce1e HTTP/1.1
content-type: application/json

{
    "username": "testuser1",
    "email": "test1@gmail.com",
    "password": "pass123",
    "phoneno": "1234567890"
}

###

POST http://localhost:4000/add/business HTTP/1.1
content-type: application/json

{
    "email": "test2@gmail.com",
    "businessname": "avocado",
    "tagline": "we suffer so you don't",
    "whatsappno": "138927348923742",
    "address": "jharkhand",
    "websiteurl": "http://website.com"
    
}

###

POST http://localhost:4000/add/political HTTP/1.1
content-type: application/json

{
    "email": "test2@gmail.com",
    "partylogo": "dafwersfdfassdfsdf.jpg",
    "facebook": "facebook",
    "twitter": "facebook",
    "instagram": "twitter",
    "designation1": "designation1",
    "designation2": "designation2"
}


###

POST http://localhost:4000/signin HTTP/1.1
content-type: application/json

{
    "email": "test5@gmail.com",
    "password": "pass123"
}

###

GET http://localhost:4000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InRlc3QxQGdtYWlsLmNvbSIsImlhdCI6MTY1OTE5MjE1MX0.pHcTXkRvsAqv5KH2T0czNHDU35cQsXOebKHDW7_6e5A


###

POST http://localhost:4000/randomno HTTP/1.1
content-type: application/json

{
    "email": "saifkhan501721@gmail.com"
}

###

POST http://localhost:4000/verifyemail HTTP/1.1
content-type: application/json

{
    "email": "test2@gmail.com",
    "randomno" : 168886
}